<a href="https://colab.research.google.com/github/CharlesRajaR/Loan-Approval-Prediction-with-SHAP-An-end-to-end-machine-learning-project/blob/main/loan_approval_prediction_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
print("Hello World!")

Hello World!

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import os
import shutil

gdrive_path = '/content/drive/MyDrive/Kaggle/datasets/loan_default_prediction/cleaned_loan_data.csv'
local_data_dir = '/data/'
local_path = os.path.join(local_data_dir, 'cleaned_loan_data.csv')

try:

    if not os.path.exists(local_data_dir):
        os.makedirs(local_data_dir)
        print(f"Created directory: {local_data_dir}")


    if not os.path.exists(local_path):
        print("Copying dataset to /data/ path...")
        shutil.copy(gdrive_path, local_path)
        print("Copy complete.")


    df = pd.read_csv(local_path, low_memory=False)
    print(f"Dataset loaded successfully from: {local_path}")
    display(df.head())
except Exception as e:
    print(f"An error occurred: {e}")

Copying dataset to /data/ path...
Copy complete.
Dataset loaded successfully from: /data/cleaned_loan_data.csv

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,home_ownership,...,debt_settlement_flag,emp_length_encoded,issue_year,issue_month,months_since_issue,zip_code_encoded,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
0,3600.0,3600.0,3600.0,36.0,13.99,123.03,C,C4,leadman,MORTGAGE,...,N,10,2015.0,12.0,36.0,190.0,1.0,2019.0,3.0,2019.0
1,24700.0,24700.0,24700.0,36.0,11.99,820.28,C,C1,Engineer,MORTGAGE,...,N,10,2015.0,12.0,36.0,577.0,6.0,2016.0,3.0,2019.0
2,20000.0,20000.0,20000.0,60.0,10.78,432.66,B,B4,truck driver,MORTGAGE,...,N,10,2015.0,12.0,36.0,605.0,6.0,2017.0,3.0,2019.0
3,35000.0,35000.0,35000.0,60.0,14.85,829.90,C,C5,Information Systems Officer,MORTGAGE,...,N,10,2015.0,12.0,36.0,76.0,2.0,2019.0,3.0,2019.0
4,10400.0,10400.0,10400.0,60.0,22.45,289.91,F,F1,Contract Specialist,MORTGAGE,...,N,3,2015.0,12.0,36.0,174.0,7.0,2016.0,3.0,2018.0

In [5]:
pd.set_option('display.max_columns', None)
df.head(1)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_encoded,issue_year,issue_month,months_since_issue,zip_code_encoded,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
0,3600.0,3600.0,3600.0,36.0,13.99,123.03,C,C4,leadman,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,Debt consolidation,PA,5.91,0.0,2003-08-01 00:00:00,675.0,679.0,1.0,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,122.67,564.0,560.0,0.0,1.0,Individual,0.0,722.0,144904.0,9300.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N,10,2015.0,12.0,36.0,190.0,1.0,2019.0,3.0,2019.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Data columns (total 95 columns):
 #   Column                      Dtype
---  ------                      -----
 0   loan_amnt                   float64
 1   funded_amnt                 float64
 2   funded_amnt_inv             float64
 3   term                        float64
 4   int_rate                    float64
 5   installment                 float64
 6   grade                       object
 7   sub_grade                   object
 8   emp_title                   object
 9   home_ownership              object
 10  annual_inc                  float64
 11  verification_status         object
 12  loan_status                 object
 13  pymnt_plan                  object
 14  purpose                     object
 15  title                       object
 16  addr_state                  object
 17  dti                         float64
 18  delinq_2yrs                 float64
 19  earliest_cr_line            object
 20  fico_range_low              float64
 21  fico_range_high             float64
 22  inq_last_6mths              float64
 23  open_acc                    float64
 24  pub_rec                     float64
 25  revol_bal                   float64
 26  revol_util                  float64
 27  total_acc                   float64
 28  initial_list_status         object
 29  out_prncp                   float64
 30  out_prncp_inv               float64
 31  total_pymnt                 float64
 32  total_pymnt_inv             float64
 33  total_rec_prncp             float64
 34  total_rec_int               float64
 35  total_rec_late_fee          float64
 36  recoveries                  float64
 37  collection_recovery_fee     float64
 38  last_pymnt_amnt             float64
 39  last_fico_range_high        float64
 40  last_fico_range_low         float64
 41  collections_12_mths_ex_med  float64
 42  policy_code                 float64
 43  application_type            object
 44  acc_now_delinq              float64
 45  tot_coll_amt                float64
 46  tot_cur_bal                 float64
 47  total_rev_hi_lim            float64
 48  acc_open_past_24mths        float64
 49  avg_cur_bal                 float64
 50  bc_open_to_buy              float64
 51  bc_util                     float64
 52  chargeoff_within_12_mths    float64
 53  delinq_amnt                 float64
 54  mo_sin_old_il_acct          float64
 55  mo_sin_old_rev_tl_op        float64
 56  mo_sin_rcnt_rev_tl_op       float64
 57  mo_sin_rcnt_tl              float64
 58  mort_acc                    float64
 59  mths_since_recent_bc        float64
 60  mths_since_recent_inq       float64
 61  num_accts_ever_120_pd       float64
 62  num_actv_bc_tl              float64
 63  num_actv_rev_tl             float64
 64  num_bc_sats                 float64
 65  num_bc_tl                   float64
 66  num_il_tl                   float64
 67  num_op_rev_tl               float64
 68  num_rev_accts               float64
 69  num_rev_tl_bal_gt_0         float64
 70  num_sats                    float64
 71  num_tl_120dpd_2m            float64
 72  num_tl_30dpd                float64
 73  num_tl_90g_dpd_24m          float64
 74  num_tl_op_past_12m          float64
 75  pct_tl_nvr_dlq              float64
 76  percent_bc_gt_75            float64
 77  pub_rec_bankruptcies        float64
 78  tax_liens                   float64
 79  tot_hi_cred_lim             float64
 80  total_bal_ex_mort           float64
 81  total_bc_limit              float64
 82  total_il_high_credit_limit  float64
 83  hardship_flag               object
 84  disbursement_method         object
 85  debt_settlement_flag        object
 86  emp_length_encoded          int64
 87  issue_year                  float64
 88  issue_month                 float64
 89  months_since_issue          float64
 90  zip_code_encoded            float64
 91  last_pymnt_d_month          float64
 92  last_pymnt_d_year           float64
 93  last_credit_pull_d_month    float64
 94  last_credit_pull_d_year     float64
dtypes: float64(78), int64(1), object(16)
memory usage: 1.6+ GB

In [7]:
from IPython.core.formatters import catch_format_error
numerical_features = [col for col in df.columns if df[col].dtype != 'object']
categorical_features = [col for col in df.columns if df[col].dtype == 'object']

In [8]:
len(numerical_features), len(categorical_features)

(79, 16)

In [9]:
df[numerical_features].head(1)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,emp_length_encoded,issue_year,issue_month,months_since_issue,zip_code_encoded,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
0,3600.0,3600.0,3600.0,36.0,13.99,123.03,55000.0,5.91,0.0,675.0,679.0,1.0,7.0,0.0,2765.0,29.7,13.0,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,122.67,564.0,560.0,0.0,1.0,0.0,722.0,144904.0,9300.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,10,2015.0,12.0,36.0,190.0,1.0,2019.0,3.0,2019.0

In [10]:
trf = [col for col in df.columns if 'month' in col or 'year' in col]
trf

['issue_year',
 'issue_month',
 'months_since_issue',
 'last_pymnt_d_month',
 'last_pymnt_d_year',
 'last_credit_pull_d_month',
 'last_credit_pull_d_year']

In [11]:
time_related_features = ['issue_year', 'issue_month', 'months_since_issue', 'last_pymnt_d_month', "last_pymnt_d_year", "last_credit_pull_d_month", "last_credit_pull_d_year"]

In [12]:
time_related_features

['issue_year',
 'issue_month',
 'months_since_issue',
 'last_pymnt_d_month',
 'last_pymnt_d_year',
 'last_credit_pull_d_month',
 'last_credit_pull_d_year']

In [13]:
numerical_features = [col for col in numerical_features if col not in trf]

In [14]:
df.head(1)

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,home_ownership,annual_inc,verification_status,loan_status,pymnt_plan,purpose,title,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,disbursement_method,debt_settlement_flag,emp_length_encoded,issue_year,issue_month,months_since_issue,zip_code_encoded,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
0,3600.0,3600.0,3600.0,36.0,13.99,123.03,C,C4,leadman,MORTGAGE,55000.0,Not Verified,Fully Paid,n,debt_consolidation,Debt consolidation,PA,5.91,0.0,2003-08-01 00:00:00,675.0,679.0,1.0,7.0,0.0,2765.0,29.7,13.0,w,0.0,0.0,4421.723917,4421.72,3600.0,821.72,0.0,0.0,0.0,122.67,564.0,560.0,0.0,1.0,Individual,0.0,722.0,144904.0,9300.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,4.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,N,Cash,N,10,2015.0,12.0,36.0,190.0,1.0,2019.0,3.0,2019.0

In [15]:
len(numerical_features), len(categorical_features), len(trf)

(72, 16, 7)

In [16]:
pd.set_option('display.max_rows', None)
df[numerical_features].isnull().sum().sort_values(ascending=False)

mths_since_recent_inq         295468
num_tl_120dpd_2m              153690
mo_sin_old_il_acct            139104
bc_util                        76104
percent_bc_gt_75               75412
bc_open_to_buy                 74968
mths_since_recent_bc           73445
pct_tl_nvr_dlq                 70464
avg_cur_bal                    70379
mo_sin_rcnt_rev_tl_op          70310
mo_sin_old_rev_tl_op           70310
num_rev_accts                  70310
num_actv_bc_tl                 70309
num_actv_rev_tl                70309
num_tl_30dpd                   70309
total_il_high_credit_limit     70309
mo_sin_rcnt_tl                 70309
num_accts_ever_120_pd          70309
num_bc_tl                      70309
num_op_rev_tl                  70309
tot_cur_bal                    70309
total_rev_hi_lim               70309
num_il_tl                      70309
tot_coll_amt                   70309
num_rev_tl_bal_gt_0            70309
num_tl_90g_dpd_24m             70309
tot_hi_cred_lim                70309
num_tl_op_past_12m             70309
num_sats                       58623
num_bc_sats                    58623
acc_open_past_24mths           50063
total_bc_limit                 50063
total_bal_ex_mort              50063
mort_acc                       50063
revol_util                      1835
dti                             1744
pub_rec_bankruptcies            1398
chargeoff_within_12_mths         178
collections_12_mths_ex_med       178
tax_liens                        138
inq_last_6mths                    63
delinq_2yrs                       62
total_acc                         62
acc_now_delinq                    62
open_acc                          62
delinq_amnt                       62
pub_rec                           62
annual_inc                        37
zip_code_encoded                  34
last_pymnt_amnt                   33
last_fico_range_high              33
collection_recovery_fee           33
last_fico_range_low               33
policy_code                       33
recoveries                        33
total_rec_late_fee                33
revol_bal                         33
out_prncp                         33
out_prncp_inv                     33
total_pymnt                       33
total_pymnt_inv                   33
total_rec_prncp                   33
fico_range_high                   33
fico_range_low                    33
total_rec_int                     33
installment                        0
int_rate                           0
term                               0
funded_amnt                        0
loan_amnt                          0
funded_amnt_inv                    0
emp_length_encoded                 0
dtype: int64

In [17]:
count = 0
for col in numerical_features:
  if df[col].isna().sum() > 0:
    count+=1
print(len(numerical_features))
print(count)

72
65

In [18]:
for col in numerical_features:
  if df[col].isna().sum() > 0:
    df[col].fillna(df[col].median(), inplace=True)

print(len(numerical_features))

/tmp/ipykernel_1978/3428684255.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

72

In [19]:
count = 0
for col in numerical_features:
  if df[col].isna().sum() > 0:
    count+=1
print(len(numerical_features))
print(count)

72
0

In [20]:
count = 0
for col in categorical_features:
  if df[col].isnull().sum() > 0:
    count+=1
print(len(categorical_features))
print(count)

16
15

In [21]:
for col in categorical_features:
  if df[col].isnull().sum() > 0:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(len(categorical_features))

/tmp/ipykernel_1978/2968452323.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

16

In [22]:
count = 0
for col in categorical_features:
  if df[col].isnull().sum() > 0:
    count+=1
print(len(categorical_features))
print(count)

16
0

In [23]:
count = 0
for col in trf:
  if df[col].isnull().sum() > 0:
    print(f'{col} => Total count : {len(df)}, Null Count: {df[col].isnull().sum()}')
    count += 1

print(count)

issue_year => Total count : 2260701, Null Count: 33
issue_month => Total count : 2260701, Null Count: 33
months_since_issue => Total count : 2260701, Null Count: 33
last_pymnt_d_month => Total count : 2260701, Null Count: 2460
last_pymnt_d_year => Total count : 2260701, Null Count: 2460
last_credit_pull_d_month => Total count : 2260701, Null Count: 105
last_credit_pull_d_year => Total count : 2260701, Null Count: 105
7

In [24]:
trf

['issue_year',
 'issue_month',
 'months_since_issue',
 'last_pymnt_d_month',
 'last_pymnt_d_year',
 'last_credit_pull_d_month',
 'last_credit_pull_d_year']

In [25]:
year_cols = ['issue_year', 'last_pymnt_d_year', 'last_credit_pull_d_year']
for col in year_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

month_cols = ['issue_month', 'last_pymnt_d_month', 'last_credit_pull_d_month']
for col in month_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

df['months_since_issue'].fillna(df['months_since_issue'].median(), inplace=True)

/tmp/ipykernel_1978/4277318015.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_1978/4277318015.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipykernel_1978/4277318015.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['months_since_issue'].fillna(df['months_since_issue'].median(), inplace=True)

In [26]:
count = 0
for col in df.columns:
  if df[col].dtype != "object":
    if df[col].isna().sum() > 0:
      count+=1

  else:
    if df[col].isnull().sum() > 0:
      count+=1

print(count)

0

In [27]:
df.describe()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,annual_inc,dti,delinq_2yrs,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,acc_now_delinq,tot_coll_amt,tot_cur_bal,total_rev_hi_lim,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_inq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,emp_length_encoded,issue_year,issue_month,months_since_issue,zip_code_encoded,last_pymnt_d_month,last_pymnt_d_year,last_credit_pull_d_month,last_credit_pull_d_year
count,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2260701.0,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06,2.260701e+06
mean,1.504690e+04,1.504163e+04,1.502341e+04,4.291022e+01,1.309282e+01,4.458058e+02,7.799222e+04,1.882344e+01,3.068707e-01,6.985881e+02,7.025883e+02,5.768193e-01,1.161239e+01,1.975224e-01,1.665838e+04,5.033767e+01,2.416249e+01,4.206830e+03,4.205904e+03,1.208252e+04,1.206435e+04,9.505735e+03,2.431374e+03,1.518431e+00,1.438770e+02,2.398222e+01,3.429305e+03,6.876612e+02,6.755400e+02,1.814437e-02,1.0,4.147828e-03,2.254937e+02,1.405250e+05,3.428863e+04,4.510104e+00,1.335438e+04,1.119688e+04,5.797738e+01,8.463746e-03,1.236949e+01,1.260000e+02,1.809476e+02,1.383673e+01,8.226016e+00,1.543083e+00,2.449253e+01,6.759637e+00,4.846514e-01,3.655043e+00,5.609891e+00,4.754108e+00,7.703810e+00,8.338380e+00,8.207755e+00,1.394228e+01,5.559976e+00,1.161184e+01,5.940635e-04,2.726146e-03,8.035826e-02,2.074368e+00,9.429802e+01,4.227050e+01,1.281142e-01,4.676824e-02,1.762541e+05,5.073154e+04,2.304111e+04,4.338879e+04,6.195811e+00,2.015858e+03,6.752579e+00,3.095436e+01,5.094367e+02,5.036217e+00,2.017631e+03,4.364122e+00,2.018394e+03
std,9.190182e+03,9.188350e+03,9.192269e+03,1.086711e+01,4.832103e+00,2.671717e+02,1.126953e+05,1.417788e+01,8.672199e-01,3.301015e+01,3.301102e+01,8.859560e-01,5.640785e+00,5.705081e-01,2.294815e+04,2.470304e+01,1.198737e+01,7.343203e+03,7.342297e+03,9.901317e+03,9.896925e+03,8.321797e+03,2.679721e+03,1.184151e+01,7.481587e+02,1.312247e+02,6.018213e+03,7.296992e+01,1.110968e+02,1.508073e-01,0.0,6.961561e-02,8.385048e+03,1.585547e+05,3.618790e+04,3.129939e+00,1.625147e+04,1.635674e+04,2.810130e+01,1.048057e-01,7.264548e+02,5.172391e+01,9.564449e+01,1.728993e+01,9.072999e+00,1.885542e+00,3.184802e+01,5.603627e+00,1.331995e+00,2.291220e+00,3.331646e+00,3.000798e+00,4.629462e+00,7.255879e+00,4.615591e+00,7.920520e+00,3.243368e+00,5.571262e+00,2.616932e-02,5.528710e-02,4.860507e-01,1.802067e+00,8.952810e+00,3.561801e+01,3.645142e-01,3.775225e-01,1.790733e+05,4.939347e+04,2.277300e+04,4.440789e+04,3.734493e+00,1.792640e+00,3.409527e+00,2.161162e+01,3.110733e+02,3.226226e+00,1.636439e+00,2.912004e+00,1.091661e+00
min,5.000000e+02,5.000000e+02,0.000000e+00,3.600000e+01,5.310000e+00,4.930000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,6.100000e+02,6.140000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.500000e-09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.007000e+03,1.000000e+00,0.000000e+00,7.000000e+00,1.000000e+00,2.007000e+03,1.000000e+00,2.007000e+03
25%,8.000000e+03,8.000000e+03,8.000000e+03,3.600000e+01,9.490000e+00,2.516500e+02,4.600000e+04,1.190000e+01,0.000000e+00,6.750000e+02,6.790000e+02,0.000000e+00,8.000000e+00,0.000000e+00,5.950000e+03,3.150000e+01,1.500000e+01,0.000000e+00,0.000000e+00,4.546650e+03,4.531860e+03,3.000000e+03,7.282000e+02,0.000000e+00,0.000000e+00,0.000000e+00,3.103300e+02,6.540000e+02,6.500000e+02,0.000000e+00,1.0,0.000000e+00,0.000000e+00,2.997900e+04,1.500000e+04,2.000000e+00,3.163000e+03,1.815000e+03,3.630000e+01,0.000000e+00,0.000000e+00,9.900000e+01,1.180000e+02,4.000000e+00,3.000000e+00,0.000000e+00,6.000000e+00,3.000000e+00,0.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,3.000000e+00,5.000000e+00,8.000000e+00,3.000000e+00,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,9.170000e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.200400e+04,2.126100e+04,8.500000e+03,1.548800e+04,3.000000e+00,2.015000e+03,4.000000e+00,1.300000e+01,2.300000e+02,3.000000e+00,2.017000e+03,3.000000e+00,2.018000e+03
50%,1.290000e+04,1.287500e+04,1.280000e+04,3.600000e+01,1.262000e+01,3.779900e+02,6.500000e+04,1.784000e+01,0.000000e+00,6.900000e+02,6.940000e+02,0.000000e+00,1.100000e+01,0.000000e+00,1.132400e+04,5.030000e+01,2.200000e+01,0.000000e+00,0.000000e+00,9.329720e+03,9.309675e+03,7.000000e+03,1.525940e+03,0.000000e+00,0.000000e+00,0.000000e+00,6.005700e+02,6.990000e+02,6.950000e+02,0.000000e+00,1.0,0.000000e+00,0.000000e+00,7.924000e+04,2.540000e+04,4.000000e+00,7.335000e+03,5.442000e+03,6.020000e+01,0.000000e+00,0.000000e+00,1.300000e+02,1.640000e+02,8.000000e+00,6.000000e+00,1.000000e+00,1.400000e+01,5.000000e+00,0.000000e+00,3.000000e+00,5.000000e+00,4.000000e+00,7.000000e+00,6.000000e+00,7.000000e+00,1.200000e+01,5.000000e+00,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,1.000000e+02,3.750000e+01,0.000000e+00,0.000000e+00,1.142985e+05,3.786400e+04,1.630000e+04,3.269600e+04,7.000000e+00,2.016000e+03,7.000000e+00,2.900000e+01,4.710000e+02,3.000000e+00,2.018000e+03,3.000000e+00,2.019000e+03
75%,2.000000e+04,2.000000e+04,2.000000e+04,6.000000e+01,1.599000e+01,5.933200e+02,9.300000e+04,2.448000e+01,0.000000e+00,7.150000e+02,7.190000e+02,1.000000e+00,1.400000e+01,0.000000e+00,2.024600e+04,6.930000e+01,3.100000e+01,6.149670e+03,6.146140e+03,1.694069e+04,1.691655e+04,1.389856e+04,3.107990e+03,0.000000e+00,0.000000e+00,0.000000e+00,3.743590e+03,7.340000e+02,7.300000e+02,0.000000e+00,1.0,0.000000e+00,0.000000e+00,2.081530e+05,4.230000e+04,6.000000e+00,1.829100e+04,1.369500e+04,8.240000e+01,0.000000e+00,0.000000e+00,1.520000e+02,2.290000e+02,1.700000e+01,1.000000e+01,2.000000e+00,2.900000e+01,1.000000e+01,0.000000e+00,5.000000e+00,7.000000e+00,6.000000e+00,1.000000e+01,1.100000e+01,1.000000e+01,1.800000e+01,7.000000e+00,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+02,6.670000e+01,0.000000e+00,0.000000e+00,2.521970e+05,6.347100e+04,2.990000e+04,5.760100e+04,1.000000e+01,2.017000e+03,1.000000e+01,4.400000e+01,8.010000e+02,8.000000e+00,2.019000e+03,4.000000e+00,2.019000e+03
max,4.000000e+04,4.000000e+04,4.000000e+04,6.000000e+01,3.099000e+01,1.719830e+03,1.100000e+08,9.990000e+02,5.800000e+01,8.450000e+02,8.500000e+02,3.300000e+01,1.010000e+02,8.600000e+01,2.904836e+06,8.923000e+02,1.760000e+02,4.000000e+04,4.000000e+04,6.329688e+04,6.329688e+04,4.000000e+04,2.819250e+04,1.484340e+03,3.985955e+04,7.174719e+03,4.219205e+04,8.500000e+02,8.450000e+02,2.000000e+01,1.0,1.400000e+01,9.152545e+06,9.971659e+06,9.999999e+06,6.400000e+01,9.580840e+05,7.111400e+05,3.396000e+02,1.000000e+01,2.499250e+05,9.990000e+02,9.990000e+02,5.470000e+02,3.820000e+02,9.400000e+01,6.610000e+02,2.500000e+01,5.800000e+01,5.000000e+01,7.200000e+01,7.100000e+01,8.600000e+01,1.590000e+02,9.100000e+01,1.510000e+02,6.500000e+01,1.010000e+02,7.000000e+00,4.000000e+00,5.800000e+01,3.200000e+01,1.000000e+02,1.000000e+02,1.200000e+01,8.500000e+01,9.999999e+06,3.408095e+06,1.569000e+06,2.118996e+06,1.000000e+01,2.018000e+03,1.200000e+01,1.380000e+02,9.990000e+02,1.200000e+01,2.019000e+03,1.200000e+01,2.019000e+03

In [28]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 10.6 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [29]:
# Define 'Default' as 'Charged Off' or 'Default' and 'Non-Default' otherwise.
# Create a binary target variable where 1 indicates a 'Default' and 0 indicates 'Non-Default'.
# First, identify the statuses that represent a 'default' or high risk.
default_statuses = [
    'Charged Off',
    'Default',
    'Late (31-120 days)',
    'Does not meet the credit policy. Status:Charged Off'
]

df['is_default'] = df['loan_status'].apply(lambda x: 1 if x in default_statuses else 0)

# Drop the original 'loan_status' column as we have our binary target.
df = df.drop('loan_status', axis=1)

print("Distribution of the new target variable 'is_default':")
print(df['is_default'].value_counts(normalize=True) * 100)

# Update categorical_features list after dropping 'loan_status'
categorical_features = [col for col in categorical_features if col != 'loan_status']

Distribution of the new target variable 'is_default':
is_default
0    87.135539
1    12.864461
Name: proportion, dtype: float64

In [30]:
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

X = df.drop('is_default', axis=1)
y = df['is_default']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
del df

We need to tell CatBoost which columns are categorical

In [32]:
cat_cols = X_train.select_dtypes(include=['object', 'category']).columns.tolist()
cat_cols

['grade',
 'sub_grade',
 'emp_title',
 'home_ownership',
 'verification_status',
 'pymnt_plan',
 'purpose',
 'title',
 'addr_state',
 'earliest_cr_line',
 'initial_list_status',
 'application_type',
 'hardship_flag',
 'disbursement_method',
 'debt_settlement_flag']

In [33]:
cat_features_index = [X_train.columns.get_loc(col) for col in cat_cols]
cat_features_index

[6, 7, 8, 9, 11, 12, 13, 14, 15, 18, 27, 42, 82, 83, 84]

In [38]:
model = CatBoostClassifier(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    cat_features=cat_features_index,
    loss_function='Logloss',
    task_type="GPU",
    devices='0',
    verbose=100,
    random_state=42,
    early_stopping_rounds=100
)

In [39]:
model.fit(X_train, y_train, eval_set=(X_test, y_test))

0:	learn: 0.5592226	test: 0.5592357	best: 0.5592357 (0)	total: 675ms	remaining: 11m 14s
100:	learn: 0.0141959	test: 0.0144440	best: 0.0144440 (100)	total: 47.1s	remaining: 6m 58s
200:	learn: 0.0110084	test: 0.0114729	best: 0.0114729 (200)	total: 1m 34s	remaining: 6m 16s
300:	learn: 0.0099302	test: 0.0105786	best: 0.0105786 (300)	total: 2m 22s	remaining: 5m 31s
400:	learn: 0.0092630	test: 0.0100849	best: 0.0100849 (400)	total: 3m 10s	remaining: 4m 44s
500:	learn: 0.0087568	test: 0.0097638	best: 0.0097634 (498)	total: 3m 58s	remaining: 3m 57s
600:	learn: 0.0083936	test: 0.0095636	best: 0.0095634 (599)	total: 4m 48s	remaining: 3m 11s
700:	learn: 0.0081186	test: 0.0094219	best: 0.0094219 (700)	total: 5m 37s	remaining: 2m 23s
800:	learn: 0.0078949	test: 0.0093408	best: 0.0093408 (800)	total: 6m 26s	remaining: 1m 35s
900:	learn: 0.0076278	test: 0.0092075	best: 0.0092075 (900)	total: 7m 15s	remaining: 47.9s
999:	learn: 0.0072763	test: 0.0089979	best: 0.0089974 (995)	total: 8m 4s	remaining: 0us
bestTest = 0.008997365062
bestIteration = 995
Shrink model to first 996 iterations.

CatBoostClassifier(cat_features=[6, 7, 8, 9, 11, 12, 13, 14, 15, 18, 27, 42, 82, 83, 84], depth=8, devices='0', early_stopping_rounds=100, iterations=1000, learning_rate=0.05, loss_function='Logloss', random_state=42, task_type='GPU', verbose=100)

In [40]:
y_pred = model.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# For ROC AUC, we need probability predictions for the positive class
y_pred_proba = model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"ROC AUC Score: {roc_auc:.4f}")

Accuracy: 0.9976

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    393609
           1       1.00      0.98      0.99     58532

    accuracy                           1.00    452141
   macro avg       1.00      0.99      0.99    452141
weighted avg       1.00      1.00      1.00    452141

ROC AUC Score: 0.9996